### PR TITLE
removed overflow

### PR DESCRIPTION
**Pull request by SyntappZ**

### CODE REVIEW

**Comment by DavidMatthewFraser** [comment]
Thanks for resolving that

**Comment by DavidMatthewFraser** [comment]
Looks good!

**Comment by DavidMatthewFraser** [comment]
@SyntappZ a guy in the Gitter said ur cool

**Comment by SyntappZ** [comment]
@DavidMatthewFraser that's awesome 😊, there's been a lot going on on that gitter by the looks of it, I never get a notification or anything it's weird

**Comment by SyntappZ** [comment]
I be more active again on Sunday or Monday I'm usually out a lot most weekends so don't have much time to code

**Comment by DavidMatthewFraser** [comment]
@SyntappZ that's fine man, do literally whateva you feel like doing, it's no worries!

**Pull request merged**
