### PR TITLE
Themes to homepage

### PR DESCRIPTION
**Pull request by DavidMatthewFraser**

### CODE REVIEW

**Comment by SyntappZ** [comment]
@DavidMatthewFraser 

This is a good idea mate, i will add a theme to it on monday too themes are cool, you knows what would be even better is if you added the theme to local storage too, so that way when someone picks a theme it stays their theme every time they use the site, this is usually the idea on most sites anyway as it would just get annoying having to pick your theme every time, might a good learning task for you if you've never used localStorage before 🙂

**Comment by terrifricker** [comment]
I was thinking about it, but it seemed to need to get rid of a lot of bootstrap html.  I'd like to practice CSS grid.

**Comment by SyntappZ** [comment]
@terrifricker i feel the same way i never use it basically, mainly because i would rather learn css thats why if you look at my html files theres no bootstrap, but truth is once people get into jobs a lot of them use bootstrap too to save time so knowing it too will defo help you still in the long run, but you should be able to understand css defo before you jump into bootstrap mate 😃

**Comment by DavidMatthewFraser** [comment]
@SyntappZ Thanks m8, I have not used localStorage before should be a good puzzle. Also I'll try to call the function from the js file. Good ideas!

@terrifricker yea I guess we use a lot of bootstrap (mostly because I'm lazy), but maybe we can add a project that's good for css grid, you’re certainly welcome to make one 😄.

**Pull request merged**
