### PR TITLE
minor panel fix and new scrollbar

### PR DESCRIPTION
**Pull request by SyntappZ**

### CODE REVIEW

**Comment by DavidMatthewFraser** [comment]
### I agree with your minor panel fixes
### I really like the choice of color for the side scroller
### One thing, when I open the 'comments slide', I get two side scrollers:
# image

### I don't think you have to necessarily get rid of one, 
### but I wonder if there's a way for them to be farther apart.
### what if the scroller for 'contributors' was on the left of the panel?
### What are your thoughts?

**Comment by SyntappZ** [comment]
Yeah your right mate i didn't see that on mine, i think the panel looks better without the scroll bar anyway so i have removed it altogether and just kept the main scroll bar as is.

**Comment by SyntappZ** [comment]
you think this looks better? just testing this out atm, the white circle is repos, im thinking i might remove it because people wont know what it is aint it,
just have followers what ya think?

**Comment by DavidMatthewFraser** [comment]
Thanks for fixing the 'two side scrollers' issue. I think showing 'Followers' and 'Repos' looks cool, however it's not clear what the 'Repo' indicator is for. If you want to keep the 'Repo' indicator for now, that's alight because it looks cool 😄. What do you think?

**Comment by DavidMatthewFraser** [comment]
We'll figure those indicators out for sure. Otherwise, the changes are good!

**Comment by SyntappZ** [comment]
Yeah im just trying some other things out cuz that repo thing is a bit random lol

**Comment by SyntappZ** [comment]
ya think this looks better? 






or maybe we use roles, people can give themselves a roll if they want



or

**Pull request merged**
