### PR TITLE
Working on a branch called Grid Play

### PR DESCRIPTION
**Pull request by terrifricker**
Don't merge yet, I will continue to make commits to this branch.

### CODE REVIEW

**Comment by terrifricker** [comment]
Oops.  I thought I was just pushing these to my repository branch.  Looks like I should have stopped with the push command and not opened a pull request.  I thought I was making a pull request to my own repository.  I guess I still don't clearly get exactly what the process is.  **What is the difference between upstream and origin?**

**Comment by terrifricker** [comment]
If I am thinking correctly, this pull request can be closed, because the commits have been made to a local branch on my computer, then pushed to the branch of same name at my GitHub repository.  Right?

**Comment by DavidMatthewFraser** [comment]
Correct! You have made changes on your local machine and pushed them to origin (which is your forked version of the branch), but you also made a pull request to merge 'grid-play' DavidMatthewFraser:master. 

If it wasn't clear, origin is your remote copy of easy-to-git and upstream is my copy of easy-to-git

**Comment by terrifricker** [comment]
Thanks, David @DavidMatthewFraser

**Pull request closed without merging**
