### PR TITLE
Spring Green Theme

### PR DESCRIPTION
**Pull request by terrifricker**
This code is actually not working currently.  I've worked a few hours to find my bug.

### CODE REVIEW

**Comment by SyntappZ** [comment]
@terrifricker hey,

you are trying to add your color variables as strings, it should be like this

`let springGreen = {
  'themeName': 'springGreen',

  'page-background': lightestgreen,
  'buttonContainer-background': darkgreen,
  'header-background': mediumgreen,
  'header-color': lightestgreen,
  'contributor-background': spring,
  'chooseTheme-background': spring,
  'btn-default-background': spring,
  'btn-primary-background': spring,
  'btn-primary-color': darkgreen,
  'comment-slide-background': spring
}`

**Comment by terrifricker** [comment]
Thanks! @DavidMatthewFraser , I don't actually like it much.  I'd rather try again.  Can you  leave it here and I'll try new colors.

**Comment by DavidMatthewFraser** [comment]
@terrifricker will do! just add another commit to this PR when your ready.

**Comment by terrifricker** [comment]
Ready.  I like this one ok.

**Comment by DavidMatthewFraser** [comment]
Looks good

**Pull request merged**
