### PR TITLE
Challenge2 Added

### PR DESCRIPTION
**Pull request by DavidMatthewFraser**

### CODE REVIEW

**Comment by DavidMatthewFraser** [comment]
@SyntappZ are you able to checkout this branch with
```
git fetch origin
git checkout -b "challenge2" "origin/challenge2"
git merge "master"
```

?

**Comment by SyntappZ** [comment]
no i get an error at the min

`git checkout -b "challenge2" "origin/challenge2"
fatal: 'origin/challenge2' is not a commit and a branch 'challenge2' cannot be created from it`

**Comment by DavidMatthewFraser** [comment]
What if you make a new clone in a separate folder and do
`git pull origin pull/60/head` (this will force an overwrite)

**Comment by DavidMatthewFraser** [comment]
Also, I can just merge the branch for now - as it changes very little of the existing code - and later figure out how to commit branches that you can actually checkout

**Comment by SyntappZ** [comment]
@DavidMatthewFraser yes it worked when i cloned from yours 😄,

Looks cool a space solar system? how did ya build this i will have to look at the code looks cool man

**Comment by DavidMatthewFraser** [comment]
Yea it is, perhaps I should do that differently

**Comment by SyntappZ** [comment]
@DavidMatthewFraser yeah probabaly better having a popup screen instructions too incase people dont want to download, you still keep the text file tho too be easy for people to read from the code side, and you could just use fetch() to fetch the instructions from the text file and show it in the popup or something so you only have to update the text file and it will update the popup too,
just a thought, anyway look fun challenge i will defo be doing it soon 😃

**Comment by DavidMatthewFraser** [comment]
@SyntappZ Yea good suggestion! Maybe you can add a pop-up menu because that's more your forte (you obviously don't have to, I can try to figure it out if ya want). I'm glad we figured out a way for you to checkout my branches. 

Alright Im going to merge if that's all good with you.

**Comment by SyntappZ** [comment]
@DavidMatthewFraser yeah i can do the popup if ya want, the css animate library will make that easy, yh its good i can see your branch now by doing a clone, theres gotta be a way i can do it from mine tho some how i will have to look into it aint it but this way will do for now aint it 😄

**Pull request merged**
