### PR TITLE
Move widgets

### PR DESCRIPTION
**Pull request by terrifricker**
I had already started moving widgets to a new page when we discussed moving them to a sidebar, but they should be easy enough to relocate.  I have two issues:
1. The logo in the header isn't displaying correctly and I can't find what needs to be changed.
2. I left the css in groupings by widget, but organized them tag, class, id within those groups.  Would you like those out of groups and organized just by the whole page?

### CODE REVIEW

**Comment by terrifricker** [comment]
I still need to add a widget button to the homepage, but it will be easier once the 'showtime' div is gone.  I tried, but it was wacky, so I'll wait and do a separate pull request for that.

**Comment by DavidMatthewFraser** [comment]
How does the user navigate to the widgets?

**Comment by terrifricker** [comment]
Yes, I've created a widgets button, but I'll need to rework it if we leave the timer in the homepage header.

**Comment by terrifricker** [comment]
Thanks for fixing all of that and adding bootstrap!  And of course we can leave the timer where it is.  I'm glad you were comfortable to just say it.

**Comment by terrifricker** [comment]
@DavidMatthewFraser I haven't figured out how to remove the underline of "Widgets" on hover.

**Comment by DavidMatthewFraser** [comment]
@terrifricker maybe something like 
```
#my-link{
text-decoration: none;
}
```
(applied to the link on the button)

**Comment by terrifricker** [comment]
Thanks! Thanks!  I used an id for my link and that worked.  I think it is ready.

**Comment by terrifricker** [comment]
Could you merge the pull request?  It may be funky because after you made commits to move-widgets branch in the main repository, I created a local branch called amended-move-widgets, but I've pushed it to the move-widgets branch here even though they don't have the same name, by moving HEAD:move-widgets(?)  See my terminal commands below:

```
Please make sure you have the correct access rights
and the repository exists.
Terri@Terris-Air easy-to-git (ammended-move-widgets) $ git push upstream
fatal: The upstream branch of your current branch does not match
the name of your current branch.  To push to the upstream branch
on the remote, use

    git push upstream HEAD:move-widgets

To push to the branch of the same name on the remote, use

    git push upstream HEAD

Terri@Terris-Air easy-to-git (ammended-move-widgets) $ git push upstream HEAD:move-widgets
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 4 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 535 bytes | 535.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/DavidMatthewFraser/easy-to-git.git
   eec3f9f..59112eb  HEAD -> move-widgets
Terri@Terris-Air easy-to-git (ammended-move-widgets) $ git status
On branch ammended-move-widgets
Your branch is up to date with 'upstream/move-widgets'.
```

**Comment by DavidMatthewFraser** [comment]
Hmmmm. Well everything looks good on my end so I'll do the merge. Good work Sir!

**Pull request merged**
