### PR TITLE
Remove old images

### PR DESCRIPTION
**Pull request by SyntappZ**
Removed the old images and added a little style to the new ones

### CODE REVIEW

**Comment by DavidMatthewFraser** [comment]
on mobile the images are larger than their containers .... but it kinda looks good that way:

Screen Shot 2020-08-19 at 6 05 18 PM


What are your thoughts with how this looks on mobile?

**Comment by SyntappZ** [comment]
@DavidMatthewFraser 

I totally forgot about responsiveness  on this 🧐 I does look pretty cool tho 😎 I can fix it if you want or ya can leave as is I'm fine either way, it's totally up to you mate 👍

**Comment by DavidMatthewFraser** [comment]
@SyntappZ I think we should look at mobile responsiveness at some point. For now I'm going to merge because it looks great on wider screens and is an improvement on mobile.
Thanks for working on the thumbnails 👍, I think they are an important part of our homepage.

**Comment by SyntappZ** [comment]
I will try make the whole page responsive today, I have noticed that the links page is broken too unless that was intentional, anyway I was thinking that them small scrolls weren't very user friendly in the first place in reality people would find that very annoying only being able to see 2 links at a time, so I think this should be changed up a bit what do you think? @DavidMatthewFraser @EmmaVZ89

**Comment by EmmaVZ89** [comment]
@SyntappZ 
I agree with you, at first I did it that way because it was the first thing that came to mind. What changes do you propose?

**Comment by SyntappZ** [comment]
@EmmaVZ89 I think it might look better without the scrolls altogether so all the links are showing and just have the page scroll down as normal, you will still be able to put some cool design on it and could still have them in their own sections and that, just think it would be a better user experience like that 😀

**Comment by DavidMatthewFraser** [comment]
I like what these guys did https://www.keycdn.com/blog/web-development-tools
perhaps we can use that as a reference

**Pull request merged**
