### PR TITLE
added my name to contributor list

### PR DESCRIPTION
**Pull request by malikmukhtar**

### CODE REVIEW

**Comment by terrifricker** [comment]
@malikmukhtar We have been using the VSCode extension "Prettier - Code Formatter".  Your formatter has different rules so it changed some formatting.  If you could run your code through Prettier, then it won't try to make so many changes.  (This  happened to me on my first pull request as well.)  Please don't hesitate to ask any questions for more information.

**Comment by malikmukhtar** [comment]
What rules should I use on the prettier?

**Comment by terrifricker** [comment]
I'm pretty sure just the defaults.  I don't remember having to change anything.

**Comment by DavidMatthewFraser** [comment]
It might be easier if you made another PR that only modifies what's necessary without changing the coding style of several entire files.

**Comment by terrifricker** [comment]
I fixed the conflicts

**Comment by terrifricker** [comment]
I'm going to merge, then worry about the syntax with a different pull request.

**Pull request merged**
