### PR TITLE
Fixed Contributing.md Add feature section

### PR DESCRIPTION
**Pull request by divyanshuParihar265**
Fixed wrong path for "Add a feature" section
* Reproduce Bug*
1. master > Contributing.md > line 35
2. see yourself

* Changes*
1. Fixed the path

### CODE REVIEW

**Comment by divyanshuParihar265** [comment]
Hey Some one Going to Look this ,

**Review by terrifricker — APPROVED** [review]
These changes look fine.

**Comment by terrifricker** [comment]
This project isn't being watched anymore.  I had posted it to twitter as an example of a type of project that could be written as an open source project.  I am no longer able to merge pull requests.

Thank you for your time in looking at the project, though.

**Comment by divyanshuParihar265** [comment]
NO problem

**Comment by terrifricker** [comment]
I have permission again to approve your merge request.  Good luck on your coding journey!

**Comment by terrifricker** [comment]
Approved

**Pull request merged**
