### PR TITLE
I added a section to share useful links

### PR DESCRIPTION
**Pull request by EmmaVZ89**
Add a section to share useful links. I await your opinions, I still need to polish it more.

### CODE REVIEW

**Comment by SyntappZ** [comment]
@EmmaVZ89 

wow what a great idea, looks good too,  the black text and the link text on the yellow background might be a bit hard to read for some people, but other than that great job mate 🙂

**Comment by EmmaVZ89** [comment]
@SyntappZ 

Thank you !. I did not take into account the background color, I will modify it for a lighter tone.

**Comment by DavidMatthewFraser** [comment]
I think it looks great too! I like how you kept the format consistent with other pages. 
What if we made the yellow background of .info-container a little lighter so that it's easier to read.
From background: #EBE104 
Screen Shot 2020-08-11 at 4 35 54 PM
To background: #f8fa7a
Screen Shot 2020-08-11 at 4 35 14 PM

**Comment by EmmaVZ89** [comment]
@DavidMatthewFraser 

Thank you!. I think that tonality would look good.

**Comment by DavidMatthewFraser** [comment]
I updated the background color.

Thanks again for all your hard work! Perhaps we should reference this page in the ReadMe.

**Pull request merged**
