### PR TITLE
added contributor panel

### PR DESCRIPTION
**Pull request by SyntappZ**

### CODE REVIEW

**Comment by DavidMatthewFraser** [comment]
Hi, When I run your code i see:
image

But I don't see a panel that displays contributors. 
Does this feature work on your end?
I can tell you put a lot of work into this feature, I like how you separated your files, and i really like the purple banner.
Please describe how the feature is working on your end so I can figure out why the panel is not showing up.

We can try to figure this out, but also if you want to try adding a smaller feature like the purple banner you can try just adding that.

Thanks for your hard work, and I hope I'm not missing something obvious.

**Comment by SyntappZ** [comment]
yeah it works i my end mate when i click the contributors button the side panel opens with the list of contributors 



it should look like this when open.

**Comment by DavidMatthewFraser** [comment]
That looks slick! I'm about to go on a hike with some pals, but I'll get back to this feature for sure. Let's get these changes made!

**Comment by SyntappZ** [comment]
Thanks mate, i think i sorted out the conflicts i hope i done it right. later 🙃👍

**Comment by DavidMatthewFraser** [comment]
So I got your code to work by making it not modular lol. The new look is sick! Great work.

**Comment by SyntappZ** [comment]
nice one mate thanks for getting that sorted yh looking pretty cool so far 😎, yeah i only had it as  a module so i could use import, i didn't know it would mess things up lol, il try do smaller branch from now on 😌👍

**Pull request merged**
