### PR TITLE
index.html : Separate nav & widget + thumbnails

### PR DESCRIPTION
**Pull request by DavidMatthewFraser**
I separated the website navigation buttons and the 'widgets' (google search and comment slide).
I cleaned up the comment slide code
I integrated design changes into themes.js
I added thumbnail images to the nav links

### CODE REVIEW

**Comment by DavidMatthewFraser** [comment]
Thanks 😊 
Yea I agree about the images ... but I'm not sure how to go about it. I think what I have is good enough for now and should be subject for change down the road. I'm going to merge for now if you're alright with that.

**Comment by SyntappZ** [comment]
Yeah defo merge mate 😀

**Comment by DavidMatthewFraser** [comment]
oh god what have I done

**Comment by DavidMatthewFraser** [comment]
The website is acting wack, but that's just cuz its loading all the new stuff I think

**Comment by SyntappZ** [comment]
@DavidMatthewFraser `The images appear huge and warped`

 nothing like that is happening on my screen? the c2 one is big thats over 6mb in size you can squoosh that down to 50kb or something

**Pull request merged**
