### PR TITLE
fix responsive contributor panel

### PR DESCRIPTION
**Pull request by EmmaVZ89**
I tried to fix the responsive design of the contributor panel, I await your opinions.

### CODE REVIEW

**Comment by EmmaVZ89** [comment]
> hey emmavz89,
> 
> Thanks for making it more responsive but doing it this way will make everything squash together on opening and closing and makes it jump, can you try and fix the jumping so its a more smooth transition before we merge, thanks 🙂

I'm going to try to do it, I don't like that transition very much either, I don't want to touch the JavaScript document a lot because I'm just starting to study it, but we'll see what elegant solution we can find.

**Comment by SyntappZ** [comment]
@DavidMatthewFraser 
Yeah it was because the width was set to 400px so any phones with less width than 400px it would be to big for the page, the easiest way around this would be to give the panel a max-width of 400px and width of 100% that way it will shrink when the screen goes bellow 400px.

I still like what @EmmaVZ89 has done tho it looks pretty cool and its good to try different things out and experiment, best way to learn i think

**Comment by EmmaVZ89** [comment]
What I fix (or try xD) is that the panel doesn't constantly occupy a space. Otherwise when the panel was hidden it kept occupying the space of its assigned width (400px). Then I changed the transition from top to bottom because from side to side the content looked somewhat tight as SyntappZ told me.
I wouldn't know what to say about the response time, the first time you press the button it takes a while but then it normalizes. It must be by taking the data from our profiles ???

**Comment by SyntappZ** [comment]
@EmmaVZ89 yeah it has to fetch data from each persons github so about 10 requests at once so it takes a while on first load, i think i might add a loading screen at the start until all data is loaded, or someone else could make one if they want

**Comment by EmmaVZ89** [comment]
@SyntappZ  I do not think it is necessary, the wait only happens when one touches the button just when entering the page, maybe we are talking about 2 seconds, at least that is what I noticed.

**Comment by DavidMatthewFraser** [comment]
For now should we make the width of panel 100% for screens less than 400px or even like 500px?

**Comment by SyntappZ** [comment]
@DavidMatthewFraser yeah make it max-width 400px so it scales down for mobile

**Comment by EmmaVZ89** [comment]
@DavidMatthewFraser  I think 400px would be enough.

**Pull request merged**
