### PR TITLE
Add new theme "Autumn Theme"

### PR DESCRIPTION
**Pull request by OdinVerst**
#223

### CODE REVIEW

**Comment by DavidMatthewFraser** [comment]
Thanks for adding the theme!
Do you feel done with the theme?
You may consider making another commit where you add more Autumn colors to the theme.
Right now I only see yellow, black, blue, and gray.

**Comment by OdinVerst** [comment]
Hello, thanks for the feedback. I changed the colors)

**Comment by terrifricker** [comment]
Lovely!  My favorite color is Orange.  Thanks for contributing.

**Comment by DavidMatthewFraser** [comment]
Great changes 👍

**Pull request merged**
