### PR TITLE
I have a commit I need to delete, but can't figure out how

### PR DESCRIPTION
**Pull request by terrifricker**
This can wait until later.  Don't interrupt your work now.

I cannot git rid of commit ba2797d.

It looks like the last item is a problem, too.  I think I made a pull request to my own repository? and merged it?  That probably doesn't need to be accepted either.  

My middle commit just adds 4 new thumbnails that are all the same size.

### CODE REVIEW

**Comment by SyntappZ** [comment]
@terrifricker this is a problem because this is your master branch so you cant just delete it, this is one reason why you should always make a new branch before adding a new feature.

What i can do is get the images from your branch and il merge them alone from a separate branch, but your still going to have to remove this commit on your end `Merge remote-tracking branch 'upstream/davidsBranch'`, i think the best way will to go back to the first branch before that commit then fetch the upstream.
 
I will try and find some instructions for you to do this soon mate 👍

**Comment by SyntappZ** [comment]
@terrifricker im gonna merge the commits now and i think `Merge remote-tracking branch 'upstream/davidsBranch'` should be gone on the next commit hopefully we will have to see on your next commit, remember to make a new branch before making new commits in future just in case something gets messed up 😄

**Comment by terrifricker** [comment]
Thank you so much, Martyn!

**Comment by SyntappZ** [comment]
@terrifricker 

no problem man, thanks for making these images i think they look better this way and now that they are all the same size i think we can make fit the image container better. 👍

**Pull request merged**
