### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by SyntappZ**
fixed overflow issue on challenge 2

### CODE REVIEW

**Comment by SyntappZ** [comment]
whats going on here?

**Comment by DavidMatthewFraser** [comment]
Yea that's what I was wondering

**Comment by DavidMatthewFraser** [comment]
Why does it say your trying to merge into DavidMatthewFraser:minor-fixes instead of DavidMatthewFraser:master

**Comment by SyntappZ** [comment]
think its because i named the branch minor-fixes can we delete this branch il just make a new one

**Pull request closed without merging**
