### PR TITLE
Readme edit

### PR DESCRIPTION
**Pull request by terrifricker**
changed a link

### CODE REVIEW

**Comment by terrifricker** [comment]
Oops.  I got mixed in with your commits somehow.

**Comment by terrifricker** [comment]
? Here is a copy of something I didn't understand in terminal that may have got me merged into your branch???
The last bolded command is the problem, I think.  

I started by trying to delete the branch I used to change the sentence in READMD  branch 'edit-tiny-errors'

Terris-Air:easy-to-git Terri$ **git branch -d edit-tiny-errors**
error: _Cannot delete_ branch 'edit-tiny-errors' checked out at '/Users/Terri/Documents/Websites/easyToGitLocal/easy-to-git/easy-to-git'
Terris-Air:easy-to-git Terri$ git branch
* edit-tiny-errors
  grid-play
  master
Terris-Air:easy-to-git Terri$ **git switch master**
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 13 commits.
  (use "git push" to publish your local commits)
Terris-Air:easy-to-git Terri$ **git branch -d edit-tiny-errors**
**warning: deleting branch 'edit-tiny-errors' that has been merged to
         'refs/remotes/origin/edit-tiny-errors', but not yet merged to HEAD.
Deleted branch edit-tiny-errors (was bd2c95b).**
Terris-Air:easy-to-git Terri$ git fetch
Terris-Air:easy-to-git Terri$ **git fetch upstream**
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 44 (delta 25), reused 42 (delta 24), pack-reused 0
Unpacking objects: 100% (44/44), done.
**From https://github.com/DavidMatthewFraser/easy-to-git
   4538604..044dd73  davidsBranch -> upstream/davidsBranch
   437f993..7f91c2b  master       -> upstream/master**
Terris-Air:easy-to-git Terri$ **git merge upstream/master**
Updating 437f993..7f91c2b
Fast-forward
 README.md | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
Terris-Air:easy-to-git Terri$ git fetch upstream
Terris-Air:easy-to-git Terri$ **git merge upstream/davidsBranch**
Merge made by the 'recursive' strategy.
 assets/css/style.css            |  77 +++++++++++++++++++++++++++-----------------------------
 assets/img/thumbnails/.DS_Store | Bin 0 -> 6148 bytes
 assets/img/thumbnails/c1.png    | Bin 0 -> 804920 bytes
 assets/img/thumbnails/c2.png    | Bin 0 -> 6878270 bytes
 assets/img/thumbnails/quiz.png  | Bin 0 -> 144912 bytes
 assets/img/thumbnails/ul.png    | Bin 0 -> 88266 bytes
 assets/js/themes.js             |  46 ++++++++++++++++++++++++----------
 index.html                      | 131 ++++++++++++++++++++++++++++++++++++++++++++----------------------------------------------------
 8 files changed, 130 insertions(+), 124 deletions(-)
 create mode 100644 assets/img/thumbnails/.DS_Store
 create mode 100644 assets/img/thumbnails/c1.png
 create mode 100644 assets/img/thumbnails/c2.png
 create mode 100644 assets/img/thumbnails/quiz.png
 create mode 100644 assets/img/thumbnails/ul.png

**Comment by terrifricker** [comment]
I'm closing this request because I pulled in some of David's commits that are already on his last pull request.

**Comment by SyntappZ** [comment]
@terrifricker 

yeah it looks like `git merge upstream/davidsBranch` this is what merged the 2 branches, also `git branch -d edit-tiny-errors
warning: deleting branch 'edit-tiny-errors' that has been merged to
'refs/remotes/origin/edit-tiny-errors', but not yet merged to HEAD.
Deleted branch edit-tiny-errors ` this is just a warning you can use `git merge edit-tiny-errors` to merge it to master before you delete it or use a capital D `git branch -D edit-tiny-errors` to delete the.

Also by you making this error i now know how to merge davids branches into mine so thanks for that 😄  👍

**Comment by terrifricker** [comment]
Good that my mistake helped. 🤪

**Comment by terrifricker** [comment]
I still have a problem, because I updated my master (fetch/merge) then created a new branch to make my change, but when I pushed the new branch, and click pull request, David's commits are still being shown.  How do I get unmerged?

**Comment by terrifricker** [comment]
the opposite of - `git merge upstream/davidsBranch`

**Comment by terrifricker** [comment]
@SyntappZ  forgot to mention you, so I will in case that is how you get notifications

**Comment by SyntappZ** [comment]
@terrifricker 

i think you can use `git reset --hard ` to go back to your last commit

**Pull request closed without merging**
