### PR TITLE
bye bye switch

### PR DESCRIPTION
**Pull request by DavidMatthewFraser**

### CODE REVIEW

**Comment by DavidMatthewFraser** [comment]
changeTheme() only accepts objects so this a way to store objects in local storage as strings and  de-stringify them when passing them

**Comment by SyntappZ** [comment]
@DavidMatthewFraser noice 😀, 

Just gives one less thing to worry about this way, plus it's always best to have DRY principles is mind when coding, I knew this would be an easy one for you.

**Comment by DavidMatthewFraser** [comment]
@terrifricker https://www.youtube.com/watch?v=k8yJCeuP6I8

**Comment by terrifricker** [comment]
@DavidMatthewFraser , thanks!

**Pull request merged**
