### PR TITLE
We continue with the changes.

### PR DESCRIPTION
**Pull request by EmmaVZ89**

### CODE REVIEW

**Comment by DavidMatthewFraser** [comment]
This design is very visually appealing and user friendly! Really good job Emma 👍

**Comment by EmmaVZ89** [comment]
@DavidMatthewFraser 
Yes, it is a good idea to do that. What else should I change in the instructions?

**Comment by DavidMatthewFraser** [comment]
Maybe instruction 2. could go from `Then place the container div with the class info-container, inside it are the containers that must be modified.` to `Each source type is wrapped in a div of class .list and all these divs are wrapped in a div of class .info-container`

**Review by SyntappZ — APPROVED** [review]
@EmmaVZ89  

This page is looking really great now mate i love the pop out menu 👍 one thing i noticed about it that could be improved is you have to click the title for it to work, you could put the li tag inside the a tag so this will act like a full button `<a href="#websites"><li>Useful websites</li></a>`  its coming along great mate keep it up 😄

**Comment by EmmaVZ89** [comment]
@SyntappZ 
Oh it's true !. Now I fix it. Sometimes I get so excited when what I wanted to do finally comes out that I don't realize those mistakes 😄

**Pull request merged**
