### PR TITLE
Added water tracker project - React project

### PR DESCRIPTION
**Pull request by sauravk7077**

### CODE REVIEW

**Comment by DavidMatthewFraser** [comment]
This looks awesome, I'll need some time to look over this new feature. Thanks for the contribution!

**Comment by terrifricker** [comment]
@sauravk7077 Would this challenge be something we work on all together to produce one Water Tracker or would we each work on our own Water Tracker and then post them on a Water Tracker webpage?

**Comment by sauravk7077** [comment]
@terrifricker .It's a team project, we should work together to make this one Water Tracker.

**Comment by DavidMatthewFraser** [comment]
@sauravk7077 I think this project is a really good way for people to get started with React, but it should probably be its own project. Easy-to-git should mostly stick to vanilla HTML, CSS, and JS in order to make it as easy as possible for new contributors to get starting with Git/Github. I think a project that's dedicated to getting people started on React would do very well and maybe you can consider doing this with your water tracker app, I'm sure there's interest out there for something  like that.

**Pull request closed without merging**
