### PR TITLE
added instruction modal/popup

### PR DESCRIPTION
**Pull request by SyntappZ**
added modal for the instructions

### CODE REVIEW

**Comment by SyntappZ** [comment]
you think any better with modal instructions? im gonna do your challenge next

**Comment by DavidMatthewFraser** [comment]
pngguru is such a good resource for this exercise!
The popup looks really good!
For some reason I can't see the instructions:
image
Is this the same of your end?

**Comment by SyntappZ** [comment]
@DavidMatthewFraser  thats weird it should have text, it works on mine 😕

**Comment by DavidMatthewFraser** [comment]
Let me try one more thing

**Comment by DavidMatthewFraser** [comment]
Screen Shot 2020-08-12 at 7 19 11 PM

Im on chrome fyi

**Comment by DavidMatthewFraser** [comment]
Screen Shot 2020-08-12 at 7 21 25 PM
If this is helpful

**Comment by DavidMatthewFraser** [comment]
I have something from 7:30 to 8:30 so I will get back to this afterwards. 
I really appreciate your work on this challenge, it's weird that the same code is acting differently between us.

**Comment by SyntappZ** [comment]
what code editor? and are you using live-server? i dont get any errors on vs-code i dont have es lint on it either

**Comment by SyntappZ** [comment]
yeah use live server otherwise the browser will block it as file://

**Comment by SyntappZ** [comment]
ok mate speak later then, the code works its just blocking on your end because you are viewing from a file instead of a web server,
so you have something like this in your url bar `file:///C:/Users/easy-to-git-new/challenges/challenge2.html` so the browser will block it, run it from a local server and it should be sorted mate

later 👍

**Comment by DavidMatthewFraser** [comment]
That did the trick! The live server is a really helpful tool, thanks for the advice! 👍

Thanks again for making the popup, looks super 😁

**Pull request merged**
